In [1]:
import sys
import os

import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

import sqlite3

sys.path.insert(0, os.path.join(os.getcwd(), '..'))
from framework import init_env
init_env()

path = os.path.join("..", os.environ["DB_FILE"])
database = sqlite3.connect(path)

### Selecteer hier over welke editie dit rapport gaat

In [ ]:
edition = 2025

In [2]:
# Ophalen van de data
sql = """
SELECT O1.position, A.name, S.rowid AS song_id, S.title, S.year, (
	SELECT position
	FROM Occurance O2
	WHERE edition = {last}
	AND O1.song = O2.song
) AS pos_last, (
    SELECT COUNT(rowid)
    FROM OCCURANCE O3
    WHERE O3.edition <= {current} AND O1.song = O3.song
) As occurance_count
FROM OCCURANCE O1 
INNER JOIN Song S ON S.rowid = O1.song
INNER JOIN Artist A ON A.rowid = S.artist
WHERE O1.edition = {current}
ORDER BY O1.position ASC
""".format(last=edition - 1, current=edition)

df = pd.read_sql_query(sql, database).set_index("position")
df.describe()

           song_id         year     pos_last  occurance_count
count  2000.000000  2000.000000  1874.000000       2000.00000
mean   2600.510500  1992.303000   949.305229         16.75900
std    1508.559999    16.930372   556.908552          9.03763
min       1.000000  1956.000000     1.000000          1.00000
25%    1262.000000  1979.000000   469.250000          9.00000
50%    2675.000000  1990.000000   939.500000         17.00000
75%    3926.500000  2006.000000  1420.750000         27.00000
max    4933.000000  2025.000000  2000.000000         27.00000

# De top 10

In [3]:
df.head(10)

,name,song_id,title,year,pos_last,occurance_count
position,,,,,,
1,Queen,3135,Bohemian Rhapsody,1975,1.0,27
2,Billy Joel,420,Piano Man,1973,5.0,27
3,Eagles,1211,Hotel California,1977,3.0,27
4,Coldplay,835,Fix You,2005,2.0,17
5,Danny Vera,4708,Roller Coaster,2019,4.0,7
6,Pearl Jam,2996,Black,1992,10.0,17
7,Led Zeppelin,2295,Stairway To Heaven,1971,7.0,27
8,Boudewijn de Groot,573,Avond,1997,8.0,27
9,Golden Earring,1656,Radar Love (Albumversie),1973,20.0,27
10,Pink Floyd,3070,Wish You Were Here,1975,12.0,26

# Grootse stijgers/zakkers

In [4]:
df['climb_rate'] = df['pos_last'] - df.index

## Grootste stijgers

In [5]:
df.sort_values(by=['climb_rate'], ascending=False).head(20)

,name,song_id,title,year,pos_last,occurance_count,climb_rate
position,,,,,,,
116,Marco Borsato,2496,Zij,2002,1566.0,14,1450.0
35,Marco Borsato,2501,De Waarheid,1996,1428.0,27,1393.0
82,Marco Borsato,2495,Afscheid Nemen Bestaat Niet,2003,1276.0,20,1194.0
93,Marco Borsato,2502,Ik Leef Niet Meer Voor Jou,1996,1238.0,26,1145.0
90,Marco Borsato,2498,De Bestemming,1998,1202.0,25,1112.0
830,The Beach Boys,3802,Sloop John B,1966,1931.0,27,1101.0
355,Benson Boone,4886,Beautiful Things,2024,1434.0,2,1079.0
182,"Marco Borsato, Armin van Buuren & Davina Michelle",4770,Hoe Het Danst,2019,1261.0,6,1079.0
910,Suzan & Freek,4737,Dromen In Kleur,2021,1962.0,4,1052.0
53,Marco Borsato,2494,Rood,2006,989.0,20,936.0
554,Chappell Roan,4887,"Good Luck, Babe!",2024,1447.0,2,893.0
590,BLØF,473,Wat Zou Je Doen?,1998,1452.0,23,862.0
956,Michael Jackson,2638,The Way You Make Me Feel,1987,1783.0,16,827.0
947,One Direction,2893,Night Changes,2014,1763.0,2,816.0
127,Marco Borsato,2493,Margherita,1996,886.0,27,759.0
533,Suzan & Freek,4732,Blauwe Dag,2019,1260.0,7,727.0
1216,Golden Earring,1664,Weekend Love,1979,1887.0,26,671.0
1218,The Beatles,3834,Sgt. Pepper's Lonely Hearts Club Band,1967,1872.0,27,654.0
188,Fleetwood Mac,1466,Silver Springs,1976,836.0,2,648.0
714,Jeff Buckley,1955,"Lover, You Should've Come Over",1994,1347.0,3,633.0

## Grootste zakkers

In [6]:
df.sort_values(by=['climb_rate'], ascending=True).head(20)

,name,song_id,title,year,pos_last,occurance_count,climb_rate
position,,,,,,,
1814,Queen,3171,It's A Beautiful Day,1995,644.0,5,-1170.0
1612,Claude,4856,Ladada (Mon Dernier Mot),2022,528.0,3,-1084.0
1958,Queen,3170,Good Old-Fashioned Lover Boy,1976,1035.0,6,-923.0
1879,Niall Horan,4664,Heaven,2023,1004.0,2,-875.0
1757,The Rolling Stones,4049,Brown Sugar,1971,884.0,27,-873.0
1993,Coldplay,846,Speed Of Sound,2005,1126.0,20,-867.0
1965,Taylor Swift,4553,You Need To Calm Down,2019,1101.0,3,-864.0
1877,David Bowie,1001,Changes,1971,1036.0,11,-841.0
1867,DI-RECT,1124,OMG It's Happening,2023,1071.0,2,-796.0
1893,Rondé,4832,Hard To Say Goodbye,2021,1111.0,4,-782.0
1951,U2 & Green Day,4571,The Saints Are Coming,2006,1174.0,11,-777.0
1467,Adele,90,Chasing Pavements,2008,718.0,17,-749.0
1413,One Direction,2891,Best Song Ever,2013,691.0,5,-722.0
1700,David Bowie & Mick Jagger,1008,Dancing In The Street,1985,986.0,26,-714.0
1645,Taylor Swift,4556,Karma,2023,963.0,2,-682.0
1750,Metallica,2608,The Unforgiven III,2008,1072.0,11,-678.0
1961,Bee Gees,371,You Should Be Dancing,1976,1294.0,15,-667.0
1721,Harry Styles,4644,Watermelon Sugar,2020,1057.0,6,-664.0
1835,Anouk,248,Girl,2004,1199.0,21,-636.0
1940,Lenny Kravitz,2310,Are You Gonna Go My Way?,1993,1323.0,17,-617.0

# Nieuwe binnenkomers

In [7]:
new_entries = df[df.pos_last.isnull()].drop(columns=['pos_last'])
print(new_entries['name'].count())

126

## Re-entries
De volgende nieuwe binnenkomers hebben al eens eerder in de top2000 gestaan:

In [8]:
re_entries = new_entries[new_entries['occurance_count'] > 1]
row_count = len(re_entries.index)
print("Aantal re-entries: {}".format(row_count))
pd.set_option('display.max_rows', row_count)
display(re_entries)

Aantal re-entries: 53

,name,song_id,title,year,occurance_count,climb_rate
position,,,,,,
404,The Beach Boys,3803,Tears In The Morning,1970,24,NaN
872,Gerard Cox,1614,'T Is Weer Voorbij Die Mooie Zomer,1973,13,NaN
1288,Golden Earring,1676,The Devil Made Me Do It,1982,4,NaN
1442,Rob de Nijs,3321,Jan Klaassen De Trompetter,1973,15,NaN
1453,Marco Borsato,2506,Vrij Zijn,1995,8,NaN
1513,Suzan & Freek,4739,Honderd Keer,2022,2,NaN
1526,Suzan & Freek,4738,Kwijt,2022,2,NaN
1535,Suzan & Freek,4735,Weg Van Jou,2020,4,NaN
1558,Lionel Richie,2349,All Night Long (All Night),1983,19,NaN
1569,2 Brothers On The 4th Floor,4590,Never Alone,1993,4,NaN
1575,B.B. King,301,The Thrill Is Gone,1969,25,NaN
1591,Twenty One Pilots,4581,Ride,2016,2,NaN
1594,Dua Lipa,4666,Be The One,2016,5,NaN
1609,Clash,3907,Should I Stay Or Should I Go,1982,15,NaN
1631,Suzan & Freek,4736,Onderweg Naar Later,2021,3,NaN
1677,Simply Red,3558,Sunrise,2003,18,NaN
1691,The Beach Boys,3804,Wouldn't It Be Nice,1966,21,NaN
1694,Bob Marley & The Wailers,527,One Love / People Get Ready,1984,19,NaN
1724,Queen,3172,Made In Heaven,1991,3,NaN
1745,Robbie Williams,3344,Come Undone,2003,6,NaN
1747,The Beatles,3842,Twist And Shout,1963,24,NaN
1762,George Michael,1601,I Can't Make You Love Me,1997,6,NaN
1768,The Police,4030,Don't Stand So Close To Me,1980,18,NaN
1769,André Hazes,208,Uit M'n Bol,1993,4,NaN
1773,Eagles,1224,Take It To The Limit,1975,5,NaN
1778,Golden Earring,1671,Sound Of The Screaming Day,1967,25,NaN
1787,Jan Smit,1923,Als De Morgen Is Gekomen,2006,14,NaN
1790,BLØF,474,Later Als Ik Groter Ben,2012,11,NaN
1822,Twenty One Pilots,4579,Heathens,2016,8,NaN
1826,Sade,3437,No Ordinary Love,1992,14,NaN
1828,Whitesnake,4385,Is This Love,1987,7,NaN
1832,Bob Dylan,521,Don't Think Twice It's All Right,1963,4,NaN
1848,De Jeugd Van Tegenwoordig,1040,Hollereer,2008,3,NaN
1857,Natalie Imbruglia,2768,Torn,1997,18,NaN
1859,George Michael,1603,Kissing A Fool,1988,6,NaN
1880,Golden Earring,1663,I've Just Lost Somebody,1968,18,NaN
1881,René Klijn,3294,Mr. Blue,1993,22,NaN
1892,Bloem,462,Even Aan M'n Moeder Vragen,1980,11,NaN
1911,Christopher Cross,786,Sailing,1981,12,NaN
1924,Daft Punk,954,Around The World,1997,10,NaN
1930,Queen,3159,One Vision,1985,10,NaN
1933,Van Dik Hout,4317,Meer Dan Een Ander,1994,10,NaN
1942,Rufus & Chaka Khan,3425,Ain't Nobody,1984,21,NaN
1947,Donna Summer,1164,Last Dance,1978,13,NaN
1949,Supertramp,3724,It's Raining Again,1982,20,NaN
1953,Roxette,3408,The Look,1989,10,NaN
1964,Tina Turner,4184,What's Love Got To Do With It,1984,21,NaN
1971,Kensington,2217,Bridges,2017,7,NaN
1976,Herman van Veen,1787,Toveren,1987,22,NaN
1977,Sting,3693,Moon Over Bourbon Street,1985,19,NaN
1983,Chic,753,Le Freak,1978,26,NaN
1988,Golden Earring,1678,Johnny Make Believe,1994,2,NaN
1992,Mumford & Sons,2739,Lover Of The Light,2012,12,NaN

## Echt nieuwe liedjes
De volgende nieuwe binnenkomers hebben nog nooit in de top2000 gestaan

In [9]:
real_new = new_entries[new_entries['occurance_count'] == 1].drop(columns=['occurance_count'])
row_count = len(real_new.index)
print("Aantal echt nieuwe liedjes: {}".format(row_count))
pd.set_option('display.max_rows', row_count)
display(real_new)

Aantal echt nieuwe liedjes: 73

,name,song_id,title,year,climb_rate
position,,,,,
33,Suzan & Freek,4741,Lichtje Branden,2021,NaN
153,René Karst,4913,Atje Voor De Sfeer,2019,NaN
306,Stef Ekkel & René Karst,4914,Liever Te Dik In De Kist Dan Weer Een Feestje ...,2019,NaN
311,Lola Young,4915,Messy,2024,NaN
357,Ozzy Osbourne,4630,Crazy Train,1980,NaN
391,Bente,4903,Kan Je Me Zien,2025,NaN
400,Suzan & Freek,4740,Niemand,2025,NaN
460,Radiohead,3222,Let Down,1997,NaN
473,Iron Maiden,1870,The Number Of The Beast,1982,NaN
614,Black Sabbath,458,Iron Man (Albumversie),1970,NaN
694,Taylor Swift,4558,The Fate Of Ophelia,2025,NaN
713,Sophie Straat,4916,"Vrijheid, Gelijkheid, Zusterschap",2023,NaN
779,RAYE,4904,Where Is My Husband!,2025,NaN
815,Alex Warren,4905,Ordinary,2025,NaN
834,Olivia Dean,4909,Man I Need,2025,NaN
884,K3,4917,Oya Lélé,2003,NaN
899,Sabrina Carpenter,4885,Taste,2024,NaN
931,Acda en De Munnik,74,De Stad Amsterdam,1997,NaN
963,Fontaines D.C.,4919,In The Modern World,2024,NaN
974,Teddy Swims,4853,Bad Dreams,2024,NaN
1008,Alex Warren,4906,Carry You Home,2024,NaN
1010,Taylor Swift,4559,August,2020,NaN
1015,Dr. Dre ft. Snoop Dogg,4687,Still D.R.E.,2001,NaN
1062,Gracie Abrams,4920,That's So True,2024,NaN
1127,Roxy Dekker,4883,Satisfyer,2023,NaN
1132,Olivia Dean,4910,Dive,2023,NaN
1133,Billie Eilish,4720,Lunch,2024,NaN
1143,DI-RECT,1125,My Blood,2024,NaN
1145,Son Mieux,4813,Have A Little Faith,2024,NaN
1151,Meau,4796,Stukje Van Mij,2024,NaN
1154,Ozzy Osbourne,4631,Dreamer,2001,NaN
1156,Coldplay,868,All My Love,2024,NaN
1157,K3,4918,Heyah Mama,2000,NaN
1223,Chris Stapleton & Dua Lipa,4921,Think I'm In Love with You (Live),2024,NaN
1303,Sef,4922,De Leven,2011,NaN
1366,Rosé ft. Bruno Mars,4923,APT.,2024,NaN
1396,Pommelien Thijs & Meau,4924,Het Midden,2024,NaN
1427,Beyoncé,403,Texas Hold 'Em,2024,NaN
1439,"Coldplay, Little Simz, Burna Boy, Elyanna, TINI",4925,We Pray,2024,NaN
1440,Taylor Swift ft. Post Malone,4926,Fortnight,2024,NaN
1452,Eminem,4502,Houdini,2024,NaN
1457,Gruppo Sportivo,1706,Hey Girl,1978,NaN
1478,De Sjonnies,4927,Dans Je De Hele Nacht Met Mij,1995,NaN
1497,Hiigo,4928,Tankstation,2023,NaN
1518,Suzan & Freek,4742,Slapeloosheid,2023,NaN
1520,Empire Of The Sun,4899,We Are The People,2008,NaN
1532,The Beach Boys,3815,Surfin' U.S.A.,1963,NaN
1545,Pommelien Thijs,4911,Atlas,2025,NaN
1566,Froukje,4825,Kwijt,2024,NaN
1642,DI-RECT,1126,All In Vain,2014,NaN
1663,Damiano David,4929,Born With A Broken Heart,2024,NaN
1679,Post Malone ft. Morgan Wallen,4930,I Had Some Help,2024,NaN
1742,2 Brothers On The 4th Floor,4592,Dreams,1994,NaN
1754,Frank Ocean,4873,Pink + White,2016,NaN
1777,Suzan & Freek,4743,Nooit Meer Regen,2023,NaN
1809,Lee Towers,2304,Mijn Feyenoord,1998,NaN
1829,HUNTR/X,4912,Golden,2025,NaN
1870,Alex Warren,4907,Burning Down,2024,NaN
1872,Chappell Roan,4888,The Subway,2025,NaN
1878,Dolly Parton,1146,Here You Come Again,1978,NaN
1884,Gorillaz,4512,Dare,2005,NaN
1891,Suzan & Freek,4744,Verleden Tijd,2024,NaN
1925,Acda en De Munnik,75,Vondelpark Vannacht,1997,NaN
1929,Rage Against The Machine,3226,Bombtrack,1994,NaN
1932,Coldplay,869,feelslikeimfallinginlove,2024,NaN
1943,Sade,3440,Is It A Crime,1985,NaN
1957,Queen,3173,The Prophet's Song,1975,NaN
1959,Alex Warren,4908,Before You Leave Me,2024,NaN
1968,Mando Diao,4931,Dance With Somebody,2009,NaN
1973,Chappell Roan,4889,Pink Pony Club,2023,NaN
1974,André Hazes & Gerard Joling,4932,Blijf Bij Mij,2007,NaN
1996,Sia,4540,Snowman,2018,NaN
1999,Lady Gaga ft. Beyoncé,4933,Telephone,2009,NaN

# Verdwenen uit de lijst
De volgende liedjes komen dit jaar niet meer voor in de top2000. De lijst is gesorteerd op jaar van uitgaven van het liedje.

In [10]:
sql = """
SELECT O.position, A.name, S.title, S.year
FROM OCCURANCE O 
INNER JOIN Song S ON S.rowid = O.song
INNER JOIN Artist A ON A.rowid = S.artist
WHERE O.edition = {last}
AND O.song NOT IN (SELECT song FROM Occurance WHERE edition={current})
ORDER  BY S.year DESC
""".format(last=edition - 1, current=edition)

ex_entries = pd.read_sql_query(sql, database).set_index("position")
row_count = len(ex_entries.index)
print("Aantal uit de lijst verdwenen: {}".format(row_count))
pd.set_option('display.max_rows', row_count)
display(ex_entries)

Aantal uit de lijst verdwenen: 126

,name,title,year
position,,,
833,Macklemore,Hind's Hall,2024
1611,The Rolling Stones,Angry,2023
1161,Douwe Bob,This World Is Our Home,2023
1806,Post Malone,Chemical,2023
1870,Sera,Head Held High,2023
1817,P!nk,Never Gonna Not Dance Again,2022
1526,Harry Styles,Music For A Sushi Restaurant,2022
1899,Flemming,Paracetamollen,2022
1344,Rondé,Love Myself,2022
1787,Rondé,Bright Eyes,2022
1958,ABBA,Don't Shut Me Down,2021
1712,John Mayer,Last Train Home,2021
1328,Taylor Swift,I Knew You Were Trouble (Taylor’s Version),2021
1397,Taylor Swift,We Are Never Ever Getting Back Together (Taylo...,2021
1998,Goldband,De Langste Nacht,2021
1493,Flemming,Amsterdam,2021
1542,P!nk ft. Willow Sage Heart,Cover Me In Sunshine,2021
1497,DI-RECT,Devil Don't Care,2019
1602,Lana Del Rey,Doin' Time,2019
1322,Harry Styles,Adore You,2019
1916,Niall Horan,Nice To Meet Ya,2019
1905,Nielson,IJskoud,2018
1639,Douwe Bob & Jacqueline Govaert,I Do,2018
1832,Ed Sheeran,Galway Girl,2017
1663,Niall Horan,Slow Hands,2017
1631,Adele,Water Under The Bridge,2016
1843,Coldplay,A Head Full Of Dreams,2016
1977,Rihanna,Love On The Brain,2016
1607,Snollebollekes,Links Rechts,2015
1991,George Ezra,Budapest,2014
1946,Anouk & Douwe Bob,Hold Me,2014
1107,One Direction,One Way Or Another (Teenage Kicks),2013
1885,Beyoncé,Love On Top,2011
1976,Birdy,Skinny Love,2011
1622,Coldplay,Charlie Brown,2011
1776,The Script,Breakeven,2009
1833,Guus Meeuwis,Proosten,2007
1919,John Mayer,Waiting On The World To Change,2006
1944,Nick & Simon,De Soldaat,2006
1932,James Blunt,You're Beautiful,2005
1973,Damien Rice,The Blower's Daughter,2005
1506,U2,City Of Blinding Lights,2005
1957,Wolfmother,Woman,2005
1443,U2,Vertigo,2004
1891,Beyoncé,Crazy In Love,2003
1771,Elvis Presley vs. Junkie XL,A Little Less Conversation,2002
1929,P!nk,Family Portrait,2002
1911,Muse,Feeling Good,2001
1981,Robbie Williams,The Road To Mandalay (Albumversie),2001
1988,U2,Elevation,2001
1190,U2,Stuck In A Moment You Can't Get Out Of,2000
1798,Sting & Cheb Mami,Desert Rose,2000
1770,Eminem,My Name Is,1999
1969,Smash Mouth,All Star,1999
1454,Ilse DeLange,I'm Not So Tough,1998
1906,George Michael,Older,1996
1936,Guus Meeuwis & Vagant,Per Spoor (Kedeng Kedeng),1996
1880,Queen,A Winter's Tale,1996
1972,Blackstreet ft. Dr Dre,No Diggity,1996
1913,Green Day,When I Come Around,1995
1658,Michael Jackson,Will You Be There,1993
1949,Pearl Jam,Rearviewmirror,1993
1992,Prince,Diamonds And Pearls,1991
1926,Phil Collins,Something Happened On The Way To Heaven,1990
1894,Crowded House,Into Temptation,1989
1935,Michael Jackson,Liberian Girl,1989
1372,U2 & BB King,When Love Comes To Town,1989
1968,Traveling Wilburys,Handle With Care,1988
1772,U2,Angel Of Harlem,1988
1965,Womack & Womack,Teardrops (Albumversie),1988
1840,Bruce Springsteen,Brilliant Disguise,1987
1937,INXS,Need You Tonight,1987
1930,Joe Cocker,You Can Leave Your Hat On,1986
1867,Paul Simon,Homeless,1986
1342,Queen,Friends Will Be Friends,1986
1908,Status Quo,In The Army Now,1986
1995,Gary Moore & Phil Lynott,Out In The Fields,1985
860,Queen,Thank God It's Christmas,1984
1967,Sade,Your Love Is King,1984
1490,Billy Joel,Uptown Girl,1983
1836,Bob Marley & The Wailers,Buffalo Soldier,1983
1857,Dolly Dots,Love Me Just A Little Bit More (Totally Hooked...,1983
1978,Doe Maar,Nachtzuster,1982
1814,Joe Cocker & Jennifer Warnes,Up Where We Belong,1982
1758,Marvin Gaye,Sexual Healing,1982
1971,Roxy Music,More Than This,1982
1873,Vitesse,Rosalyn,1982
1881,Dan Hartman,Relight My Fire,1980
1805,Paul Simon,Late In The Evening,1980
1900,Willie Nelson,On The Road Again,1980
1374,Bob Marley & The Wailers,Is This Love,1979
1820,Billy Joel,Honesty,1978
1868,Boney M,Rivers Of Babylon,1978
1649,Dire Straits,Water Of Love,1978
1801,Herman Brood,Still Believe,1978
1927,Babys,Isn't It Time,1977
1802,Billy Ocean,Love Really Hurts Without You,1976
1629,Elton John,Sorry Seems To Be The Hardest Word,1976
1907,Santana,Europa (Earth's Cry Heaven's Smile),1976
1961,John Denver,Thank God I'm A Country Boy,1975
1966,Paul McCartney & Wings,Live And Let Die,1973
1053,Quincy Jones,Chump Change,1973
1845,Boudewijn de Groot,Als De Rook Om Je Hoofd Is Verdwenen,1972
1938,Eagles,Peaceful Easy Feeling,1972
1904,Ten Years After,I'm Going Home,1971
1888,The Doors,Love Her Madly,1971
1970,Creedence Clearwater Revival,Lookin' Out My Back Door,1970
1749,Curtis Mayfield,Move On Up,1970
1737,The Rolling Stones,Midnight Rambler,1969
1595,Elvis Presley,Guitar Man,1968
1897,Otis Redding,I've Got Dreams To Remember,1968
1940,Jefferson Airplane,Somebody To Love,1967
1834,The Beatles,Lucy In The Sky With Diamonds,1967
1989,The Beatles,When I'm Sixty-Four,1967
1697,The Beatles,She's Leaving Home,1967
1963,The Doors,Break On Through (To The Other Side),1967
1635,Tim Hardin,How Can We Hang On To A Dream,1967
1799,Marvin Gaye & Tammi Terrell,Ain't No Mountain High Enough,1967
1320,The Beatles,Michelle,1966
1983,The Beatles,For No One,1966
1883,The Beatles,Here There And Everywhere,1966
1952,Roy Orbison,"Oh, Pretty Woman",1964
1241,Elvis Presley,(You're) The Devil In Disguise,1963
1815,Elvis Presley,Are You Lonesome Tonight?,1961
1912,Ella Fitzgerald & Louis Armstrong,Summertime,1958
1934,Fats Domino,Blueberry Hill,1957